### ISSUE TITLE
Create local git hub code space

### ISSUE THREAD

**Issue by liles-eric** [liles-eric/kennt#2]
---
id: github.setup.task
title: Set Up GitHub Repository with Local and Cloud Workflow
desc: A task to track the full setup of the GitHub repository, managing it locally with VS Code, Git, and Dendron, and using GitHub features like Issues, Projects, and Labels.
date: 2024-10-12
status: todo
milestone: [[github.project.kennt]]
tags: [GitHub, Setup, Azure, Dendron, High Priority]
labels: [priority-high, azure-general, type-new, request-me]
---

## Description
This **To-Do task** tracks the full setup of the GitHub repository, from cloud to local workflow using Visual Studio Code, Git, and Dendron. Key steps include setting up the repository, creating a project board, managing issues, pushing changes locally, using Codespaces, and setting up a Dendron documentation structure.

## Steps:
1. [ ] **Create GitHub repository**.
2. [ ] **Set up a GitHub Project** for tracking tasks.
3. [ ] **Create issue templates** (e.g., To-Do, Feature Request).
4. [ ] **Set up GitHub Codespaces** for cloud-based development.
5. [ ] **Clone the repository locally** using Git.
6. [ ] **Install Visual Studio Code** and set up Git integration.
7. [ ] **Create a `.gitignore` file** with appropriate rules.
8. [ ] **Install Dendron extension** in VS Code and initialize workspace.
9. [ ] **Create initial Dendron documentation** for the project structure.
10. [ ] **Stage, commit, and push changes** back to GitHub.

## Links
- [[github.project.kennt]] (Kennt Project Board)
- [[dendron.label.document]] (Label Structure and Color Theory)

## Priority:
High

## Assignee:
Yourself

## Milestone:
[[github.project.kennt]]

## Additional Notes:
This **To-Do task** ensures the project is managed in GitHub both locally and in the cloud, using Codespaces, with a Dendron structure for documentation.
